server:
  port: 18085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: search
  suffix: .html
  main:
    allow-bean-definition-overriding: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  #rabbitmq:
  #  host: 192.168.25.138
# 生成静态页的位置
#pagepath: D:/project/workspace_changgou/changgou/changgou-parent/changgou-web/changgou-web-search/src/main/resources/templates/items